# Generated by Django 5.0.6 on 2024-05-16 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TtaCndnAmtC',
            fields=[
                ('customer_guid', models.CharField(max_length=32, verbose_name='Customer guid')),
                ('child_guid', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='Child guid')),
                ('seq', models.IntegerField(blank=True, null=True, verbose_name='Sequence')),
                ('itemcode', models.CharField(blank=True, max_length=20, null=True, verbose_name='Item Code')),
                ('description', models.CharField(blank=True, db_column='Description', max_length=60, null=True, verbose_name='Description')),
                ('qty', models.FloatField(blank=True, db_column='Qty', null=True, verbose_name='Quantity')),
                ('amount_c', models.FloatField(blank=True, null=True, verbose_name='Amount')),
                ('gst_tax_type', models.CharField(blank=True, max_length=5, null=True, verbose_name='GST Tax Type')),
                ('gst_tax_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='GST Tax Code')),
                ('gst_tax_rate', models.FloatField(blank=True, null=True, verbose_name='GST Tax Rate')),
                ('gst_tax_amount', models.FloatField(blank=True, null=True, verbose_name='GST Tax Amount')),
                ('amount_c_include_tax', models.FloatField(blank=True, null=True, verbose_name='Amount Including Tax')),
                ('remark', models.CharField(blank=True, max_length=50, null=True, verbose_name='Remark')),
                ('created_at', models.DateTimeField(blank=True, null=True, verbose_name='Created at')),
                ('created_by', models.CharField(blank=True, max_length=20, null=True, verbose_name='Created by')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Updated at')),
                ('updated_by', models.CharField(blank=True, max_length=20, null=True, verbose_name='Updated by')),
                ('dept', models.CharField(blank=True, db_column='Dept', max_length=5, null=True, verbose_name='Department')),
                ('subdept', models.CharField(blank=True, db_column='SubDept', max_length=5, null=True, verbose_name='Sub Department')),
                ('category', models.CharField(blank=True, db_column='Category', max_length=5, null=True, verbose_name='Category')),
                ('brand', models.CharField(blank=True, db_column='Brand', max_length=5, null=True, verbose_name='Brand')),
                ('manufacturer', models.CharField(blank=True, db_column='Manufacturer', max_length=5, null=True, verbose_name='Manufacturer')),
                ('barcode', models.CharField(blank=True, db_column='Barcode', max_length=30, null=True, verbose_name='Barcode')),
                ('reason', models.CharField(blank=True, max_length=20, null=True, verbose_name='Reason')),
                ('itemtype', models.CharField(blank=True, max_length=35, null=True, verbose_name='Item Type')),
                ('ori_inv_no', models.CharField(blank=True, max_length=30, null=True, verbose_name='Original Invoice Number')),
                ('ori_inv_date', models.DateField(blank=True, null=True, verbose_name='Original Invoice Date')),
                ('postdatetime_c', models.DateTimeField(blank=True, null=True, verbose_name='Posted Date Time')),
                ('consign', models.SmallIntegerField(blank=True, null=True, verbose_name='Consign')),
                ('colour', models.CharField(blank=True, db_column='Colour', max_length=20, null=True, verbose_name='Colour')),
                ('size', models.CharField(blank=True, db_column='Size', max_length=20, null=True, verbose_name='Size')),
                ('articleno', models.CharField(blank=True, db_column='ArticleNo', max_length=20, null=True, verbose_name='Article Number')),
                ('packsize', models.FloatField(blank=True, db_column='PackSize', null=True, verbose_name='Pack Size')),
                ('um', models.CharField(blank=True, db_column='UM', max_length=5, null=True, verbose_name='Unit of Measurement')),
                ('itemlink', models.CharField(blank=True, db_column='ItemLink', max_length=20, null=True, verbose_name='Item Link')),
                ('hq_update', models.SmallIntegerField(blank=True, null=True, verbose_name='HQ Update')),
                ('unitprice', models.FloatField(blank=True, db_column='UnitPrice', null=True, verbose_name='Unit Price')),
                ('byamt', models.SmallIntegerField(blank=True, db_column='byAmt', null=True, verbose_name='By Amount')),
                ('gst_manual', models.SmallIntegerField(blank=True, null=True, verbose_name='GST Manual')),
                ('taxintno', models.IntegerField(blank=True, db_column='TaxIntNo', null=True, verbose_name='Tax Int Number')),
                ('taxcodemap', models.CharField(blank=True, db_column='TaxCodeMap', max_length=15, null=True, verbose_name='Tax Code Map')),
                ('taxvalue', models.FloatField(blank=True, db_column='TaxValue', null=True, verbose_name='Tax Value')),
                ('taxamount', models.FloatField(blank=True, db_column='TaxAmount', null=True, verbose_name='Tax Amount')),
                ('taxamountvariance', models.FloatField(blank=True, db_column='TaxAmountVariance', null=True, verbose_name='Tax Amount Variance')),
            ],
            options={
                'db_table': 'tta_cndn_amt_c',
                'ordering': ('child_guid', 'cndn_guid'),
                'managed': False,
            },
        ),
    ]
