# Generated by Django 5.0.6 on 2024-05-16 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DesignDynamic',
            fields=[
                ('dynamic_guid', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='Dynamic guid')),
                ('customer_guid', models.CharField(blank=True, max_length=32, null=True, verbose_name='Customer guid')),
                ('isactive', models.SmallIntegerField(blank=True, null=True, verbose_name='Is Active')),
                ('dynamic_seq', models.SmallIntegerField(blank=True, null=True, verbose_name='Dynamic sequence')),
                ('dynamic_value', models.JSONField(blank=True, null=True, verbose_name='Dynamic value')),
                ('created_at', models.DateTimeField(blank=True, null=True, verbose_name='Created at')),
                ('created_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='Created by')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Updated at')),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='Updated by')),
            ],
            options={
                'db_table': 'design_dynamic',
                'ordering': ('dynamic_seq',),
                'managed': False,
            },
        ),
    ]
