# Generated by Django 5.0.6 on 2024-05-16 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('_mc_tta_list', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TtaListMarketingSupport',
            fields=[
                ('list_guid', models.OneToOneField(db_column='list_guid', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='_mc_tta_list.ttalist', verbose_name='List guid')),
                ('list_link_guid', models.CharField(blank=True, max_length=32, null=True, verbose_name='List Link guid')),
                ('marketing_guid', models.CharField(blank=True, editable=False, max_length=36, verbose_name='Marketing Support guid')),
                ('revision', models.CharField(blank=True, max_length=100, null=True, verbose_name='Revision')),
                ('customer_guid', models.CharField(max_length=32, verbose_name='Customer guid')),
                ('refno', models.CharField(editable=False, max_length=20, verbose_name='Reference No.')),
                ('packaging_fee_value', models.FloatField(blank=True, null=True, verbose_name='Packaging Fee Value')),
                ('packaging_fee_type', models.CharField(blank=True, max_length=200, null=True, verbose_name='Packaging Fee Type')),
                ('packaging_fee_value_type', models.CharField(blank=True, max_length=200, null=True, verbose_name='Packaging Fee Value Type')),
                ('loyalty_program_value', models.FloatField(blank=True, null=True, verbose_name='Loyalty Program Value')),
                ('loyalty_program_type', models.CharField(blank=True, max_length=200, null=True, verbose_name='Loyalty Program Type')),
                ('loyalty_program_value_type', models.CharField(blank=True, max_length=200, null=True, verbose_name='Loyalty Program Value Type')),
                ('anniversary_event_value', models.FloatField(blank=True, null=True, verbose_name='Anniversary Event Value')),
                ('anniversary_event_type', models.CharField(blank=True, max_length=200, null=True, verbose_name='Anniversary Event Type')),
                ('anniversary_event_value_type', models.CharField(blank=True, max_length=200, null=True, verbose_name='Anniversary Event Value Type')),
                ('anniversary_event_date_to', models.CharField(blank=True, max_length=200, null=True, verbose_name='Anniversary Event Date To')),
                ('anniversary_event_date_from', models.CharField(blank=True, max_length=200, null=True, verbose_name='Anniversary Event Date From')),
                ('crm_event_value', models.FloatField(blank=True, null=True, verbose_name='CRM Event Value')),
                ('crm_event_type', models.CharField(blank=True, max_length=200, null=True, verbose_name='CRM Event Type')),
                ('crm_event_value_type', models.CharField(blank=True, max_length=200, null=True, verbose_name='CRM Event Value Type')),
                ('crm_event_date_to', models.CharField(blank=True, max_length=200, null=True, verbose_name='CRM Event Date To')),
                ('crm_event_date_from', models.CharField(blank=True, max_length=200, null=True, verbose_name='CRM Event Date From')),
                ('marketing_event_value', models.FloatField(blank=True, null=True, verbose_name='Marketing Event Value')),
                ('marketing_event_type', models.CharField(blank=True, max_length=200, null=True, verbose_name='Marketing Event Type')),
                ('marketing_event_value_type', models.CharField(blank=True, max_length=200, null=True, verbose_name='Marketing Event Value Type')),
                ('marketing_event_date_to', models.CharField(blank=True, max_length=200, null=True, verbose_name='Marketing Event Date To')),
                ('marketing_event_date_from', models.CharField(blank=True, max_length=200, null=True, verbose_name='Marketing Event Date From')),
                ('concourse_event_value', models.FloatField(blank=True, null=True, verbose_name='Concourse Event Value')),
                ('concourse_event_type', models.CharField(blank=True, max_length=200, null=True, verbose_name='Concourse Event Type')),
                ('concourse_event_value_type', models.CharField(blank=True, max_length=200, null=True, verbose_name='Concourse Event Value Type')),
                ('concourse_event_date_to', models.CharField(blank=True, max_length=200, null=True, verbose_name='Concourse Event Date To')),
                ('concourse_event_date_from', models.CharField(blank=True, max_length=200, null=True, verbose_name='Concourse Event Date From')),
                ('created_at', models.DateTimeField(blank=True, null=True, verbose_name='Created at')),
                ('created_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='Created by')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Updated at')),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='Updated by')),
            ],
            options={
                'verbose_name': 'TTA List Marketing Support Detail',
                'verbose_name_plural': 'TTA List Marketing Support Details',
                'db_table': 'tta_list_marketingsupport',
                'ordering': ('refno',),
                'managed': False,
            },
        ),
    ]
