# Generated by Django 5.0.6 on 2024-05-16 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TtaListStatus',
            fields=[
                ('status_key', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='Status Key')),
                ('status_description', models.CharField(blank=True, max_length=32, null=True, verbose_name='Status Description')),
                ('status_process', models.CharField(blank=True, max_length=60, null=True, verbose_name='Status Process')),
                ('created_at', models.DateTimeField(blank=True, null=True, verbose_name='Created at')),
            ],
            options={
                'db_table': 'tta_list_status',
                'ordering': ('status_description',),
                'managed': False,
            },
        ),
    ]
