# Generated by Django 5.0.6 on 2024-05-16 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TtaInvmain',
            fields=[
                ('customer_guid', models.CharField(max_length=32, verbose_name='Customer guid')),
                ('invmain_guid', models.CharField(blank=True, max_length=32, primary_key=True, serialize=False, verbose_name='Invoice Main guid')),
                ('refno', models.CharField(blank=True, max_length=20, null=True, verbose_name='Reference Number')),
                ('docno', models.CharField(blank=True, max_length=25, null=True, verbose_name='Document Number')),
                ('invoice_date', models.DateField(blank=True, null=True, verbose_name='Invoice Date')),
                ('code', models.CharField(blank=True, max_length=20, null=True, verbose_name='Code')),
                ('name', models.CharField(blank=True, max_length=60, null=True, verbose_name='Name')),
                ('add_1', models.CharField(blank=True, max_length=60, null=True, verbose_name='Address Line 1')),
                ('add_2', models.CharField(blank=True, max_length=60, null=True, verbose_name='Address Line 2')),
                ('add_3', models.CharField(blank=True, max_length=60, null=True, verbose_name='Address Line 3')),
                ('add_4', models.CharField(blank=True, max_length=60, null=True, verbose_name='Address Line 4')),
                ('attn', models.CharField(blank=True, max_length=60, null=True, verbose_name='Attn')),
                ('term', models.CharField(blank=True, max_length=20, null=True, verbose_name='Term')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='Remark')),
                ('subtotal1', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Subtotal 1')),
                ('discount1', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Discount 1')),
                ('discount1type', models.CharField(blank=True, max_length=1, null=True, verbose_name='Discount 1 Type')),
                ('subtotal2', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Subtotal 2')),
                ('discount2', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Discount 2')),
                ('discount2type', models.CharField(blank=True, max_length=1, null=True, verbose_name='Discount 2 Type')),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Total')),
                ('posted', models.IntegerField(blank=True, null=True, verbose_name='Posted')),
                ('posted_by', models.CharField(blank=True, max_length=32, null=True, verbose_name='Posted by')),
                ('posted_at', models.DateTimeField(blank=True, null=True, verbose_name='Posted at')),
                ('export_account', models.CharField(blank=True, max_length=32, null=True, verbose_name='Export Account')),
                ('export_at', models.DateTimeField(blank=True, null=True, verbose_name='Exported at')),
                ('gst_tax_sum', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='GST Tax Sum')),
                ('gst_tax_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='GST Tax Rate')),
                ('gst_adj', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='GST Adjustment')),
                ('total_incl_tax', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Total Including Tax')),
                ('doc_status', models.CharField(blank=True, max_length=32, null=True, verbose_name='Document Status')),
                ('created_at', models.DateTimeField(blank=True, null=True, verbose_name='Created at')),
                ('created_by', models.CharField(blank=True, max_length=32, null=True, verbose_name='Created by')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Updated at')),
                ('updated_by', models.CharField(blank=True, max_length=32, null=True, verbose_name='Updated by')),
            ],
            options={
                'db_table': 'tta_invmain',
                'ordering': ('refno',),
                'managed': False,
            },
        ),
    ]
