# Generated by Django 5.0.6 on 2024-05-16 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sysrun',
            fields=[
                ('sysrun_guid', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='Sysrun guid')),
                ('customer_guid', models.CharField(max_length=32, verbose_name='Customer guid')),
                ('customer_prefix', models.CharField(max_length=5, verbose_name='Customer Prefix')),
                ('type', models.CharField(blank=True, db_column='Type', max_length=10, verbose_name='Type')),
                ('code', models.CharField(blank=True, db_column='Code', max_length=10, verbose_name='Code')),
                ('currentno', models.IntegerField(blank=True, db_column='CurrentNo', null=True, verbose_name='Current No.')),
                ('nodigit', models.IntegerField(blank=True, db_column='NoDigit', null=True, verbose_name='Digit No.')),
                ('yyyy', models.IntegerField(blank=True, db_column='YYYY', null=True, verbose_name='YYYY')),
                ('mm', models.IntegerField(blank=True, db_column='MM', null=True, verbose_name='MM')),
                ('remarks', models.CharField(blank=True, db_column='Remarks', max_length=100, null=True, verbose_name='Remarks')),
            ],
            options={
                'db_table': 'sysrun',
                'ordering': ('currentno',),
                'managed': False,
            },
        ),
    ]
