# Generated by Django 5.0.6 on 2024-05-16 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RimsAccGlmaster',
            fields=[
                ('glmaster_guid', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='GL Master guid')),
                ('customer_guid', models.CharField(blank=True, max_length=32, null=True, verbose_name='Customer guid')),
                ('acc_type', models.CharField(blank=True, max_length=20, null=True, verbose_name='Account Type')),
                ('acc_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='Account Code')),
                ('acc_description', models.CharField(blank=True, max_length=60, null=True, verbose_name='Account Description')),
                ('isactive', models.SmallIntegerField(blank=True, null=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(blank=True, null=True, verbose_name='Created At')),
                ('created_by', models.CharField(blank=True, max_length=32, null=True, verbose_name='Created By')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Updated At')),
                ('updated_by', models.CharField(blank=True, max_length=32, null=True, verbose_name='Updated By')),
            ],
            options={
                'db_table': 'rims_acc_glmaster',
                'managed': False,
            },
        ),
    ]
