# Generated by Django 5.0.6 on 2024-05-16 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('_mc_tta_list', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TtaListStockNDeliveries',
            fields=[
                ('list_guid', models.OneToOneField(db_column='list_guid', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='_mc_tta_list.ttalist', verbose_name='List guid')),
                ('list_link_guid', models.CharField(blank=True, max_length=32, null=True, verbose_name='List Link guid')),
                ('stock_guid', models.CharField(blank=True, editable=False, max_length=36, verbose_name='Stock guid')),
                ('revision', models.CharField(blank=True, max_length=100, null=True, verbose_name='Revision')),
                ('customer_guid', models.CharField(max_length=32, verbose_name='Customer guid')),
                ('refno', models.CharField(editable=False, max_length=20, verbose_name='Reference No.')),
                ('cross_docking_allowance_value', models.FloatField(blank=True, null=True, verbose_name='Cross Docking Allowance')),
                ('cross_docking_allowance_type', models.CharField(blank=True, max_length=200, null=True, verbose_name='Cross Docking Allowance Type')),
                ('cross_docking_allowance_value_type', models.CharField(blank=True, max_length=200, null=True, verbose_name='Cross Docking Allowance Value Type')),
                ('conventional_flow_thru_allowance_value', models.FloatField(blank=True, null=True, verbose_name='Conventional Flow Thru Allowance Value')),
                ('conventional_flow_thru_allowance_type', models.CharField(blank=True, max_length=200, null=True, verbose_name='Conventional Flow Thru Allowance Type')),
                ('conventional_flow_thru_allowance_value_type', models.CharField(blank=True, max_length=200, null=True, verbose_name='Conventional Flow Thru Allowance Value Type')),
                ('shrinkage_pilferage_allowance_value', models.FloatField(blank=True, null=True, verbose_name='Shrinkange Pilferafe Allowance Value')),
                ('shrinkage_pilferage_allowance_type', models.CharField(blank=True, max_length=200, null=True, verbose_name='Shrinkange Pilferafe Allowance Type')),
                ('shrinkage_pilferage_allowance_value_type', models.CharField(blank=True, max_length=200, null=True, verbose_name='Shrinkange Pilferafe Allowance Value Type')),
                ('non_returnable_goods_allowance_value', models.FloatField(blank=True, null=True, verbose_name='Non Returnable Goods Allowance Value')),
                ('non_returnable_goods_allowance_type', models.CharField(blank=True, max_length=200, null=True, verbose_name='Non Returnable Goods Allowance Type')),
                ('non_returnable_goods_allowance_value_type', models.CharField(blank=True, max_length=200, null=True, verbose_name='Non Returnable Goods Allowance Value Type')),
                ('east_malaysia_orders_allowance_value', models.FloatField(blank=True, null=True, verbose_name='East Malaysia Orders Allowance Value')),
                ('east_malaysia_orders_allowance_type', models.CharField(blank=True, max_length=200, null=True, verbose_name='East Malaysia Orders Allowance Type')),
                ('east_malaysia_orders_allowance_value_type', models.CharField(blank=True, max_length=200, null=True, verbose_name='East Malaysia Orders Allowance Value Type')),
                ('damage_good_allowance_value', models.FloatField(blank=True, null=True, verbose_name='Damage Good Allowance Value')),
                ('damage_good_allowance_type', models.CharField(blank=True, max_length=200, null=True, verbose_name='Damage Good Allowance Type')),
                ('damage_good_allowance_value_type', models.CharField(blank=True, max_length=200, null=True, verbose_name='Damage Good Allowance Value Type')),
                ('non_compliance_packaging_allowance_value', models.FloatField(blank=True, null=True, verbose_name='Non-compliance Packaging Allowance')),
                ('non_compliance_packaging_allowance_type', models.CharField(blank=True, max_length=200, null=True, verbose_name='Non-compliance Packaging Allowance Type')),
                ('non_compliance_packaging_allowance_value_type', models.CharField(blank=True, max_length=200, null=True, verbose_name='Non-compliance Packaging Allowance Value Type')),
                ('purchase_order_fulfillment_value', models.FloatField(blank=True, null=True, verbose_name='Purchase Order Fulfillment Value')),
                ('purchase_order_fulfillment_type', models.CharField(blank=True, max_length=200, null=True, verbose_name='Purchase Order Fulfillment Type')),
                ('purchase_order_fulfillment_value_type', models.CharField(blank=True, max_length=200, null=True, verbose_name='Purchase Order Fulfillment Value Type')),
                ('unfulfilled_penalty_value', models.FloatField(blank=True, null=True, verbose_name='Unfulfilled Penalty Value')),
                ('unfulfilled_penalty_type', models.CharField(blank=True, max_length=200, null=True, verbose_name='Unfulfilled Penalty Type')),
                ('unfulfilled_penalty_value_type', models.CharField(blank=True, max_length=200, null=True, verbose_name='Unfulfilled Penalty Value Type')),
                ('lost_of_profit_penalty_value', models.FloatField(blank=True, null=True, verbose_name='Lost of Profit Penalty Value')),
                ('lost_of_profit_penalty_type', models.CharField(blank=True, max_length=200, null=True, verbose_name='Lost of Profit Penalty Type')),
                ('lost_of_profit_penalty_value_type', models.CharField(blank=True, max_length=200, null=True, verbose_name='Lost of Profit Penalty Value Type')),
                ('purchase_order_lead_time_value', models.FloatField(blank=True, null=True, verbose_name='Purchase Order Lead Time Value')),
                ('purchase_order_lead_time_type', models.CharField(blank=True, max_length=200, null=True, verbose_name='Purchase Order Lead Time Type')),
                ('purchase_order_lead_time_value_type', models.CharField(blank=True, max_length=200, null=True, verbose_name='Purchase Order Lead Time Value Type')),
                ('lead_time_penalty_value', models.FloatField(blank=True, null=True, verbose_name='Lead Time Penalty Value')),
                ('lead_time_penalty_type', models.CharField(blank=True, max_length=200, null=True, verbose_name='Lead Time Penalty Type')),
                ('lead_time_penalty_value_type', models.CharField(blank=True, max_length=200, null=True, verbose_name='Lead Time Penalty Value Type')),
                ('ullarge_value', models.FloatField(blank=True, null=True, verbose_name='Ullarge Value')),
                ('ullarge_type', models.CharField(blank=True, max_length=200, null=True, verbose_name='Ullarge Type')),
                ('ullarge_value_type', models.CharField(blank=True, max_length=200, null=True, verbose_name='Ullarge Value Type')),
                ('target_service_level_value', models.FloatField(blank=True, null=True, verbose_name='Target Service Level Value')),
                ('target_service_level_type', models.CharField(blank=True, max_length=200, null=True, verbose_name='Target Service Level Type')),
                ('target_service_level_value_type', models.CharField(blank=True, max_length=200, null=True, verbose_name='Target Service Level Value Type')),
                ('target_service_level_unfulfilled_penalty_value', models.FloatField(blank=True, null=True, verbose_name='Target Service Level Unfulfilled Penalty Value')),
                ('target_service_level_unfulfilled_penalty_type', models.CharField(blank=True, max_length=200, null=True, verbose_name='Target Service Level Unfulfilled Penalty Type')),
                ('target_service_level_unfulfilled_penalty_value_type', models.CharField(blank=True, max_length=200, null=True, verbose_name='Target Service Level Unfulfilled Penalty Value Type')),
                ('created_at', models.DateTimeField(blank=True, null=True, verbose_name='Created at')),
                ('created_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='Created by')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Updated at')),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='Updated by')),
            ],
            options={
                'verbose_name': 'TTA List Stock And Delivery Detail',
                'verbose_name_plural': 'TTA List Stock And Deliveries Details',
                'db_table': 'tta_list_stockndeliveries',
                'ordering': ('refno',),
                'managed': False,
            },
        ),
    ]
