# Generated by Django 5.0.6 on 2024-05-16 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DesignRow',
            fields=[
                ('row_guid', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='Row guid')),
                ('seq', models.IntegerField(blank=True, null=True, verbose_name='Sequence')),
                ('size', models.IntegerField(blank=True, null=True, verbose_name='Size')),
                ('created_at', models.DateTimeField(blank=True, null=True, verbose_name='Created at')),
                ('created_by', models.CharField(blank=True, max_length=20, null=True, verbose_name='Created by')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Updated at')),
                ('updated_by', models.CharField(blank=True, max_length=20, null=True, verbose_name='Updated by')),
            ],
            options={
                'db_table': 'design_row',
                'ordering': ('seq',),
                'managed': False,
            },
        ),
    ]
