# Generated by Django 5.0.6 on 2024-05-16 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RimsBanner',
            fields=[
                ('banner_guid', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='Banner guid')),
                ('customer_guid', models.CharField(max_length=32, verbose_name='Customer guid')),
                ('concept_guid', models.CharField(blank=True, max_length=32, null=True, verbose_name='Concept guid')),
                ('concept', models.CharField(blank=True, max_length=100, null=True, verbose_name='Concept')),
                ('concept_inactive', models.SmallIntegerField(blank=True, null=True, verbose_name='Concept Inactive')),
                ('branch_guid', models.CharField(blank=True, max_length=32, null=True, verbose_name='Branch guid')),
                ('branch', models.CharField(blank=True, max_length=100, null=True, verbose_name='Branch')),
                ('branch_inactive', models.SmallIntegerField(blank=True, null=True, verbose_name='Inactive Branch')),
            ],
            options={
                'db_table': 'rims_banner',
                'managed': False,
            },
        ),
    ]
