# Generated by Django 5.0.6 on 2024-05-16 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormOptionValue',
            fields=[
                ('option_child_guid', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='Option Child guid')),
                ('option_type', models.CharField(max_length=100, verbose_name='Option Type')),
                ('option_seq', models.IntegerField(blank=True, null=True, verbose_name='Option Sequence')),
                ('value', models.TextField(db_column='option_value')),
                ('label', models.TextField(db_column='option_description')),
                ('selected', models.CharField(db_column='option_default', max_length=10, verbose_name='Selected')),
                ('created_at', models.DateTimeField(blank=True, null=True, verbose_name='Created at')),
                ('created_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='Created by')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Updated at')),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='Updated by')),
            ],
            options={
                'db_table': 'form_option_value',
                'ordering': ('option_seq',),
                'managed': False,
            },
        ),
    ]
