# Generated by Django 3.2.7 on 2021-10-13 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormOptionValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_child_guid', models.CharField(max_length=32)),
                ('option_type', models.CharField(max_length=100)),
                ('option_value', models.CharField(max_length=100)),
                ('option_description', models.CharField(max_length=100)),
                ('option_default', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'form_option_value',
                'ordering': ('option_description',),
                'managed': False,
            },
        ),
    ]
