# Generated by Django 5.0.6 on 2024-05-16 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RimsAccCode',
            fields=[
                ('acc_guid', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='Account guid')),
                ('customer_guid', models.CharField(max_length=32, verbose_name='Customer guid')),
                ('acc_type', models.CharField(blank=True, max_length=32, null=True, verbose_name='Account Type')),
                ('tta_field', models.CharField(blank=True, max_length=32, null=True, verbose_name='TTA Field')),
                ('tta_description', models.CharField(blank=True, max_length=60, null=True, verbose_name='TTA Description')),
                ('acc_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='Account Code')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Updated at')),
                ('updated_by', models.CharField(blank=True, max_length=32, null=True, verbose_name='Updated by')),
            ],
            options={
                'db_table': 'rims_acc_code',
                'managed': False,
            },
        ),
    ]
