# Generated by Django 3.2.7 on 2021-10-13 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DesignTemplate',
            fields=[
                ('template_guid', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('json', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'design_template',
                'ordering': ('description',),
                'managed': False,
            },
        ),
    ]
