# Generated by Django 5.0.6 on 2024-05-16 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DesignTemplate',
            fields=[
                ('template_guid', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='Template guid')),
                ('description', models.CharField(blank=True, max_length=100, null=True, verbose_name='Description')),
                ('json', models.JSONField(blank=True, null=True, verbose_name='Json')),
            ],
            options={
                'db_table': 'design_template',
                'ordering': ('description',),
                'managed': False,
            },
        ),
    ]
