# Generated by Django 5.0.6 on 2024-05-16 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RimsDivDeptSdC',
            fields=[
                ('customer_guid', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='Customer guid')),
                ('trans_guid', models.CharField(max_length=32, verbose_name='Transaction guid')),
                ('group_code', models.CharField(blank=True, max_length=120, null=True, verbose_name='Group Code')),
                ('group_desc', models.CharField(blank=True, max_length=120, null=True, verbose_name='Group Description')),
                ('dept', models.CharField(blank=True, max_length=120, null=True, verbose_name='Department')),
                ('dept_desc', models.CharField(blank=True, max_length=120, null=True, verbose_name='Department Description')),
                ('subdept', models.CharField(blank=True, max_length=120, null=True, verbose_name='Subdepartment')),
                ('subdeptdesc', models.CharField(blank=True, max_length=120, null=True, verbose_name='Subdepartment Description')),
                ('category', models.CharField(blank=True, max_length=120, null=True, verbose_name='Category')),
                ('category_desc', models.CharField(blank=True, max_length=120, null=True, verbose_name='Category Description')),
            ],
            options={
                'db_table': 'rims_div_dept_sd_c',
                'ordering': ('customer_guid', 'trans_guid'),
                'managed': False,
            },
        ),
    ]
