# Generated by Django 5.0.6 on 2024-05-16 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('_mc_tta_list', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TtaListECommerceSupport',
            fields=[
                ('list_guid', models.OneToOneField(db_column='list_guid', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='_mc_tta_list.ttalist', verbose_name='List guid')),
                ('list_link_guid', models.CharField(blank=True, max_length=32, null=True, verbose_name='List Link guid')),
                ('ecommerce_guid', models.CharField(blank=True, editable=False, max_length=36, verbose_name='E-Commerce Support guid')),
                ('revision', models.CharField(blank=True, max_length=100, null=True, verbose_name='Revision')),
                ('customer_guid', models.CharField(max_length=32, verbose_name='Customer guid')),
                ('refno', models.CharField(editable=False, max_length=20, verbose_name='Reference No.')),
                ('e_commerce_sales_value', models.FloatField(blank=True, null=True, verbose_name='E-Commerce Sales Value')),
                ('e_commerce_sales_type', models.CharField(blank=True, max_length=200, null=True, verbose_name='E-Commerce Sales Type')),
                ('e_commerce_sales_value_type', models.CharField(blank=True, max_length=200, null=True, verbose_name='E-Commerce Sales Value Type')),
                ('e_commerce_sales_date_to', models.CharField(blank=True, max_length=200, null=True, verbose_name='E-Commerce Sales Date To')),
                ('e_commerce_sales_date_from', models.CharField(blank=True, max_length=200, null=True, verbose_name='E-Commerce Sales Date From')),
                ('system_setup_n_maintenance_value', models.FloatField(blank=True, null=True, verbose_name='System Setup & Maintenance Value')),
                ('system_setup_n_maintenance_type', models.CharField(blank=True, max_length=200, null=True, verbose_name='System Setup & Maintenance Type')),
                ('system_setup_n_maintenance_value_type', models.CharField(blank=True, max_length=200, null=True, verbose_name='System Setup & Maintenance Value Type')),
                ('system_setup_n_maintenance_date_to', models.CharField(blank=True, max_length=200, null=True, verbose_name='System Setup & Maintenance Date To')),
                ('system_setup_n_maintenance_date_from', models.CharField(blank=True, max_length=200, null=True, verbose_name='System Setup & Maintenance Date From')),
                ('digital_communication_value', models.FloatField(blank=True, null=True, verbose_name='Digital Communication Value')),
                ('digital_communication_type', models.CharField(blank=True, max_length=200, null=True, verbose_name='Digital Communication Type')),
                ('digital_communication_value_type', models.CharField(blank=True, max_length=200, null=True, verbose_name='Digital Communication Value Type')),
                ('digital_communication_date_to', models.CharField(blank=True, max_length=200, null=True, verbose_name='Digital Communication Date To')),
                ('digital_communication_date_from', models.CharField(blank=True, max_length=200, null=True, verbose_name='Digital Communication Date From')),
                ('social_media_post_value', models.FloatField(blank=True, null=True, verbose_name='Social Media Post Value')),
                ('social_media_post_type', models.CharField(blank=True, max_length=200, null=True, verbose_name='Social Media Post Type')),
                ('social_media_post_value_type', models.CharField(blank=True, max_length=200, null=True, verbose_name='Social Media Post Value Type')),
                ('social_media_post_date_to', models.CharField(blank=True, max_length=200, null=True, verbose_name='Social Media Post Date To')),
                ('social_media_post_date_from', models.CharField(blank=True, max_length=200, null=True, verbose_name='Social Media Post Date From')),
                ('market_place_event_value', models.FloatField(blank=True, null=True, verbose_name='Market Place Event Value')),
                ('market_place_event_type', models.CharField(blank=True, max_length=200, null=True, verbose_name='Market Place Event Type')),
                ('market_place_event_value_type', models.CharField(blank=True, max_length=200, null=True, verbose_name='Market Place Event Value Type')),
                ('market_place_event_date_to', models.CharField(blank=True, max_length=200, null=True, verbose_name='Market Place Event Date To')),
                ('market_place_event_date_from', models.CharField(blank=True, max_length=200, null=True, verbose_name='Market Place Event Date From')),
                ('created_at', models.DateTimeField(blank=True, null=True, verbose_name='Created at')),
                ('created_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='Created by')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Updated at')),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='Updated by')),
            ],
            options={
                'verbose_name': 'TTA List E-Commerce Support Detail',
                'verbose_name_plural': 'TTA List E-Commerce Support Details',
                'db_table': 'tta_list_ecommercesupport',
                'ordering': ('refno',),
                'managed': False,
            },
        ),
    ]
