# Generated by Django 5.0.6 on 2024-05-16 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SetUser',
            fields=[
                ('customer_guid', models.CharField(max_length=32, verbose_name='Customer guid')),
                ('loc_count', models.SmallIntegerField(blank=True, null=True, verbose_name='Count of Location')),
                ('loc_group', models.CharField(blank=True, max_length=32, null=True, verbose_name='Group of Location')),
                ('user_group_guid', models.CharField(blank=True, max_length=32, null=True, verbose_name='User Group guid')),
                ('user_group_name', models.CharField(blank=True, max_length=120, null=True, verbose_name='User Group Name')),
                ('user_guid', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='User guid')),
                ('user_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='User Identifier')),
                ('user_password', models.CharField(blank=True, max_length=15, null=True, verbose_name='User Password')),
                ('user_name', models.CharField(blank=True, max_length=60, null=True, verbose_name='User Name')),
                ('user_email', models.CharField(blank=True, max_length=100, null=True, verbose_name='User Email')),
                ('user_instance', models.CharField(blank=True, max_length=120, null=True, verbose_name='User Instance')),
                ('user_instance_variable', models.CharField(blank=True, max_length=120, null=True, verbose_name='User Instance Variable')),
                ('isactive', models.IntegerField(blank=True, null=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(blank=True, null=True, verbose_name='Created at')),
                ('created_by', models.CharField(blank=True, max_length=255, null=True, verbose_name='Created by')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Updated at')),
                ('updated_by', models.CharField(blank=True, max_length=255, null=True, verbose_name='Updated by')),
                ('mobile_status', models.IntegerField(blank=True, null=True, verbose_name='Mobile Status')),
            ],
            options={
                'db_table': 'set_user',
                'ordering': ('user_id',),
                'managed': False,
            },
        ),
    ]
