# Generated by Django 5.0.6 on 2024-05-16 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('_mc_tta_list', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TtaListAdministrationFees',
            fields=[
                ('list_guid', models.OneToOneField(db_column='list_guid', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='_mc_tta_list.ttalist', verbose_name='List guid')),
                ('list_link_guid', models.CharField(blank=True, max_length=32, null=True, verbose_name='List Link guid')),
                ('administration_guid', models.CharField(blank=True, editable=False, max_length=36, verbose_name='Administration guid')),
                ('revision', models.CharField(blank=True, max_length=100, null=True, verbose_name='Revision')),
                ('customer_guid', models.CharField(max_length=32, verbose_name='Customer guid')),
                ('refno', models.CharField(editable=False, max_length=20, verbose_name='Reference No.')),
                ('account_administration_fee_value', models.FloatField(blank=True, null=True, verbose_name='Account Administration Fee Value')),
                ('account_administration_fee_type', models.CharField(blank=True, max_length=200, null=True, verbose_name='Account Administration Fee Type')),
                ('account_administration_fee_value_type', models.CharField(blank=True, max_length=200, null=True, verbose_name='Account Administration Fee Value Type')),
                ('product_registration_fee_value', models.FloatField(blank=True, null=True, verbose_name='Product Registration Fee Value')),
                ('product_registration_fee_type', models.CharField(blank=True, max_length=200, null=True, verbose_name='Product Registration Fee Type')),
                ('product_registration_fee_value_type', models.CharField(blank=True, max_length=200, null=True, verbose_name='Product Registration Fee Value Type')),
                ('sku_replacement_value', models.FloatField(blank=True, null=True, verbose_name='SKU Replacement Value')),
                ('sku_replacement_type', models.CharField(blank=True, max_length=200, null=True, verbose_name='SKU Replacement Type')),
                ('sku_replacement_value_type', models.CharField(blank=True, max_length=200, null=True, verbose_name='SKU Replacement Value Type')),
                ('new_line_fee_value', models.FloatField(blank=True, null=True, verbose_name='New Line Fee Value')),
                ('new_line_fee_type', models.CharField(blank=True, max_length=200, null=True, verbose_name='New Line Fee Type')),
                ('new_line_fee_value_type', models.CharField(blank=True, max_length=200, null=True, verbose_name='New Line Fee Value Type')),
                ('new_item_listing_value', models.FloatField(blank=True, null=True, verbose_name='New Vendor Item Listing Value')),
                ('new_item_listing_type', models.CharField(blank=True, max_length=200, null=True, verbose_name='New Vendor Item Listing Type')),
                ('new_item_listing_value_type', models.CharField(blank=True, max_length=200, null=True, verbose_name='New Vendor Item Listing Value Type')),
                ('new_item_first_order_discount_value1', models.FloatField(blank=True, null=True, verbose_name='New Item First Order Discount Value 1')),
                ('new_item_first_order_discount_value2', models.FloatField(blank=True, null=True, verbose_name='New Item First Order Discount Value 2')),
                ('new_item_first_order_discount_type1', models.CharField(blank=True, max_length=200, null=True, verbose_name='New Item First Order Discount Type 1')),
                ('new_item_first_order_discount_type2', models.CharField(blank=True, max_length=200, null=True, verbose_name='New Item First Order Discount Type 2')),
                ('new_item_first_order_discount_value_type', models.CharField(blank=True, max_length=200, null=True, verbose_name='New Item First Order Discount Value Type')),
                ('change_of_purchase_type_value', models.FloatField(blank=True, null=True, verbose_name='Change of Purchase Type Value')),
                ('change_of_purchase_type_type', models.CharField(blank=True, max_length=200, null=True, verbose_name='Change of Purchase Type Type')),
                ('change_of_purchase_type_value_type', models.CharField(blank=True, max_length=200, null=True, verbose_name='Change of Purchase Type Value Type')),
                ('maintenance_of_vendor_information_value', models.FloatField(blank=True, null=True, verbose_name='Vendor Information Maintenance Value')),
                ('maintenance_of_vendor_information_type', models.CharField(blank=True, max_length=200, null=True, verbose_name='Vendor Information Maintenance Type')),
                ('maintenance_of_vendor_information_value_type', models.CharField(blank=True, max_length=200, null=True, verbose_name='Vendor Information Maintenance Value Type')),
                ('new_vcr_barcode_value', models.FloatField(blank=True, null=True, verbose_name='New Vendor Creation (By Existing Vendor Barcode) Value')),
                ('new_vcr_barcode_type', models.CharField(blank=True, max_length=200, null=True, verbose_name='New Vendor Creation (By Existing Vendor Barcode) Type')),
                ('new_vcr_barcode_value_type', models.CharField(blank=True, max_length=200, null=True, verbose_name='New Vendor Creation (By Existing Vendor Barcode) Value Type')),
                ('created_at', models.DateTimeField(blank=True, null=True, verbose_name='Created at')),
                ('created_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='Created by')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Updated at')),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='Updated by')),
            ],
            options={
                'verbose_name': 'TTA List Administration Fees Detail',
                'verbose_name_plural': 'TTA List Administration Fees Details',
                'db_table': 'tta_list_administrationfees',
                'ordering': ('refno',),
                'managed': False,
            },
        ),
    ]
