# Generated by Django 5.0.6 on 2024-05-16 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccInternal',
            fields=[
                ('trans_guid', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='Transaction guid')),
                ('internal_name', models.CharField(blank=True, max_length=60, null=True, verbose_name='Internal Name')),
                ('internal_url', models.CharField(blank=True, max_length=120, null=True, verbose_name='Internal URL Link')),
                ('created_at', models.DateTimeField(blank=True, null=True, verbose_name='Created at')),
                ('created_by', models.CharField(blank=True, max_length=32, null=True, verbose_name='Created by')),
            ],
            options={
                'db_table': 'acc_internal',
                'managed': False,
            },
        ),
    ]
