# Generated by Django 5.0.6 on 2024-05-16 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainFilterChild',
            fields=[
                ('child_filter_guid', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='Child Filter guid')),
                ('cols_size', models.IntegerField(blank=True, null=True, verbose_name='Column Size')),
                ('sm_size', models.IntegerField(blank=True, null=True, verbose_name='Small Size')),
                ('md_size', models.IntegerField(blank=True, null=True, verbose_name='Medium Size')),
                ('lg_size', models.IntegerField(blank=True, null=True, verbose_name='Large Size')),
                ('xl_size', models.IntegerField(blank=True, null=True, verbose_name='Extra Large Size')),
                ('placeholder', models.CharField(blank=True, max_length=100, null=True, verbose_name='Placeholder')),
                ('id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Identifier')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Name')),
                ('parameter', models.CharField(blank=True, max_length=100, null=True, verbose_name='Parameter')),
                ('seq', models.SmallIntegerField(blank=True, null=True, verbose_name='Sequence')),
                ('option_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Option Type')),
                ('is_active', models.SmallIntegerField(blank=True, null=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(blank=True, null=True, verbose_name='Created at')),
                ('created_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='Created by')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Updated at')),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='Updated by')),
            ],
            options={
                'db_table': 'main_filter_child',
                'ordering': ('seq',),
                'managed': False,
            },
        ),
    ]
