# Generated by Django 5.0.6 on 2024-05-16 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TtaCndnAmt',
            fields=[
                ('customer_guid', models.CharField(max_length=32, verbose_name='Customer guid')),
                ('cndn_guid', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='Cndn guid')),
                ('trans_type', models.CharField(blank=True, max_length=10, null=True, verbose_name='Transaction Type')),
                ('loc_group', models.CharField(blank=True, max_length=20, null=True, verbose_name='Location Group')),
                ('location', models.CharField(blank=True, max_length=20, null=True, verbose_name='Location')),
                ('refno', models.CharField(blank=True, max_length=20, null=True, verbose_name='Reference Number')),
                ('docno', models.CharField(blank=True, max_length=20, null=True, verbose_name='Document Number')),
                ('docdate', models.DateField(blank=True, null=True, verbose_name='Document Date')),
                ('code', models.CharField(blank=True, max_length=20, null=True, verbose_name='Code')),
                ('name', models.CharField(blank=True, max_length=80, null=True, verbose_name='Name')),
                ('tax_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Tax Code')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='Remark')),
                ('term', models.CharField(blank=True, max_length=10, null=True, verbose_name='Term')),
                ('amount', models.FloatField(blank=True, null=True, verbose_name='Amount')),
                ('gst_tax_sum', models.FloatField(blank=True, null=True, verbose_name='GST Tax Sum')),
                ('amount_include_tax', models.FloatField(blank=True, null=True, verbose_name='Amount Including Tax')),
                ('created_at', models.DateTimeField(blank=True, null=True, verbose_name='Created at')),
                ('created_by', models.CharField(blank=True, max_length=20, null=True, verbose_name='Created by')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Updated at')),
                ('updated_by', models.CharField(blank=True, max_length=20, null=True, verbose_name='Updated by')),
                ('posted', models.SmallIntegerField(blank=True, null=True, verbose_name='Posted')),
                ('posted_at', models.DateTimeField(blank=True, null=True, verbose_name='Posted at')),
                ('posted_by', models.CharField(blank=True, max_length=20, null=True, verbose_name='Posted by')),
                ('sup_cn_no', models.CharField(blank=True, max_length=20, null=True, verbose_name='Supplier CN Number')),
                ('sup_cn_date', models.DateField(blank=True, null=True, verbose_name='Supplier CN Date')),
                ('doc_name_reg', models.CharField(blank=True, max_length=80, null=True, verbose_name='Document Name Register')),
                ('gst_tax_rate', models.FloatField(blank=True, null=True, verbose_name='GST Tax Rate')),
                ('multi_tax_code', models.SmallIntegerField(blank=True, null=True, verbose_name='Multi Tax Code')),
                ('refno2', models.CharField(blank=True, max_length=20, null=True, verbose_name='Reference Number 2')),
                ('gst_adj', models.FloatField(blank=True, null=True, verbose_name='GST Adjustment')),
                ('rounding_adj', models.FloatField(blank=True, null=True, verbose_name='Rounding Adjustment')),
                ('unpostby', models.CharField(blank=True, max_length=80, null=True, verbose_name='Unpost by')),
                ('unpostdatetime', models.DateTimeField(blank=True, null=True, verbose_name='Unpost Date Time')),
                ('subdeptcode', models.CharField(blank=True, max_length=20, null=True, verbose_name='Sub Department Code')),
                ('export_account', models.CharField(blank=True, max_length=10, null=True, verbose_name='Export Account')),
                ('export_at', models.DateTimeField(blank=True, null=True, verbose_name='Exported at')),
                ('export_by', models.CharField(blank=True, max_length=30, null=True, verbose_name='Exported by')),
                ('consign', models.SmallIntegerField(blank=True, null=True, verbose_name='Consign')),
                ('hq_update', models.SmallIntegerField(blank=True, null=True, verbose_name='HQ Update')),
                ('ibt', models.SmallIntegerField(blank=True, null=True, verbose_name='IBT')),
                ('acc_posting_date', models.DateField(blank=True, null=True, verbose_name='Account Posting Date')),
                ('trans_type_acc', models.CharField(blank=True, max_length=10, null=True, verbose_name='Transaction Type Account')),
                ('doc_type', models.CharField(blank=True, max_length=10, null=True, verbose_name='Document Type')),
                ('uploaded', models.SmallIntegerField(blank=True, null=True, verbose_name='Uploaded')),
                ('uploaded_at', models.DateTimeField(blank=True, null=True, verbose_name='Uploaded at')),
                ('cndn_doutlet_code', models.CharField(blank=True, db_column='CNDN_DOutlet_code', max_length=20, null=True, verbose_name='Cndn D Outlet Code')),
                ('cndn_salesman', models.CharField(blank=True, db_column='CNDN_Salesman', max_length=30, null=True, verbose_name='Cndn Salesman')),
                ('cndn_amtasdesc', models.CharField(blank=True, db_column='CNDN_AmtAsDesc', max_length=200, null=True, verbose_name='Cndn Amount As Description')),
                ('cndn_add1', models.CharField(blank=True, db_column='CNDN_Add1', max_length=60, null=True, verbose_name='Cndn Address 1')),
                ('cndn_add2', models.CharField(blank=True, db_column='CNDN_Add2', max_length=60, null=True, verbose_name='Cndn Address 2')),
                ('cndn_add3', models.CharField(blank=True, db_column='CNDN_Add3', max_length=60, null=True, verbose_name='Cndn Address 3')),
                ('cndn_add4', models.CharField(blank=True, db_column='CNDN_Add4', max_length=60, null=True, verbose_name='Cndn Address 4')),
                ('cndn_tel', models.CharField(blank=True, db_column='CNDN_Tel', max_length=20, null=True, verbose_name='Cndn Telephone')),
                ('cndn_fax', models.CharField(blank=True, db_column='CNDN_Fax', max_length=20, null=True, verbose_name='Cndn Fax')),
                ('cndn_dadd1', models.CharField(blank=True, db_column='CNDN_DAdd1', max_length=60, null=True, verbose_name='Cndn Delivery Address 1')),
                ('cndn_dadd2', models.CharField(blank=True, db_column='CNDN_DAdd2', max_length=60, null=True, verbose_name='Cndn Delivery Address 2')),
                ('cndn_dadd3', models.CharField(blank=True, db_column='CNDN_DAdd3', max_length=60, null=True, verbose_name='Cndn Delivery Address 3')),
                ('cndn_dadd4', models.CharField(blank=True, db_column='CNDN_DAdd4', max_length=60, null=True, verbose_name='Cndn Delivery Address 4')),
                ('cndn_dtel', models.CharField(blank=True, db_column='CNDN_DTel', max_length=20, null=True, verbose_name='Cndn Delivery Telephone')),
                ('cndn_dfax', models.CharField(blank=True, db_column='CNDN_DFax', max_length=20, null=True, verbose_name='Cndn Delivery Fax')),
            ],
            options={
                'db_table': 'tta_cndn_amt',
                'ordering': ('refno', 'cndn_guid'),
                'managed': False,
            },
        ),
    ]
