# Generated by Django 5.0.6 on 2024-05-16 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TtaInvchild',
            fields=[
                ('customer_guid', models.CharField(max_length=32, verbose_name='Customer guid')),
                ('invchild_guid', models.CharField(blank=True, max_length=32, primary_key=True, serialize=False, verbose_name='Invoice Child guid')),
                ('line', models.IntegerField(blank=True, null=True, verbose_name='Line')),
                ('pricetype', models.CharField(max_length=5, verbose_name='Price Type')),
                ('itemcode', models.CharField(max_length=20, verbose_name='Item Code')),
                ('description', models.CharField(max_length=50, verbose_name='Description')),
                ('qty', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Quantity')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Unit Price')),
                ('disc1type', models.CharField(max_length=20, verbose_name='Discount 1 Type')),
                ('disc1value', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Discount 1 Value')),
                ('disc2type', models.CharField(max_length=20, verbose_name='Discount 2 Type')),
                ('disc2value', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Discount 2 Value')),
                ('totalprice', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Total Price')),
                ('gst_tax_code', models.CharField(max_length=10, verbose_name='GST Tax Code')),
                ('gst_tax_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='GST Tax Rate')),
                ('gst_tax_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='GST Tax Amount')),
                ('total_incl_tax', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Total Including Tax')),
                ('created_at', models.DateTimeField(blank=True, null=True, verbose_name='Created at')),
                ('created_by', models.CharField(blank=True, max_length=32, null=True, verbose_name='Created by')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Updated at')),
                ('updated_by', models.CharField(blank=True, max_length=32, null=True, verbose_name='Updated by')),
            ],
            options={
                'db_table': 'tta_invchild',
                'ordering': ('invchild_guid',),
                'managed': False,
            },
        ),
    ]
