# Generated by Django 5.0.6 on 2024-05-16 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DesignMainTemplate',
            fields=[
                ('customer_guid', models.CharField(blank=True, max_length=32, null=True, verbose_name='Customer guid')),
                ('main_guid', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='Main guid')),
                ('main_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Main Name')),
                ('main_description', models.CharField(blank=True, max_length=250, null=True, verbose_name='Main Description')),
                ('isactive', models.IntegerField(blank=True, null=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(blank=True, null=True, verbose_name='Created at')),
                ('created_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='Created by')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Updated at')),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='Updated by')),
            ],
            options={
                'db_table': 'design_main_template',
                'ordering': ('main_name',),
                'managed': False,
            },
        ),
    ]
