# Generated by Django 5.0.6 on 2024-05-16 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DesignComponent',
            fields=[
                ('component_guid', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='Component guid')),
                ('seq', models.IntegerField(blank=True, null=True, verbose_name='Sequence')),
                ('cols_size', models.IntegerField(blank=True, null=True, verbose_name='Column Size')),
                ('sm_size', models.IntegerField(blank=True, null=True, verbose_name='Small Size')),
                ('md_size', models.IntegerField(blank=True, null=True, verbose_name='Medium Size')),
                ('lg_size', models.IntegerField(blank=True, null=True, verbose_name='Large Size')),
                ('xl_size', models.IntegerField(blank=True, null=True, verbose_name='Extra Large Size')),
                ('offset_cols_size', models.IntegerField(blank=True, null=True, verbose_name='Offset Column Size')),
                ('offset_sm_size', models.IntegerField(blank=True, null=True, verbose_name='Offset Small Size')),
                ('offset_md_size', models.IntegerField(blank=True, null=True, verbose_name='Offset Medium Size')),
                ('offset_lg_size', models.IntegerField(blank=True, null=True, verbose_name='Offset Large Size')),
                ('offset_xl_size', models.IntegerField(blank=True, null=True, verbose_name='Offset Extra Large Size')),
                ('group', models.CharField(blank=True, max_length=200, null=True, verbose_name='Group')),
                ('input_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Input Type')),
                ('rows', models.IntegerField(blank=True, null=True, verbose_name='Rows')),
                ('id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Identifier')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Name')),
                ('placeholder', models.CharField(blank=True, max_length=100, null=True, verbose_name='Placeholder')),
                ('text', models.CharField(blank=True, max_length=200, null=True, verbose_name='Text')),
                ('type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Type')),
                ('left_label', models.CharField(blank=True, max_length=100, null=True, verbose_name='Left Label')),
                ('left_option_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Left Option Identifier')),
                ('left_option_url', models.CharField(blank=True, max_length=200, null=True, verbose_name='Left Option Url')),
                ('option_url', models.CharField(blank=True, max_length=200, null=True, verbose_name='Option Url')),
                ('dynamic', models.SmallIntegerField(blank=True, null=True, verbose_name='Dynamic')),
                ('created_at', models.DateTimeField(blank=True, null=True, verbose_name='Created at')),
                ('created_by', models.CharField(blank=True, max_length=20, null=True, verbose_name='Created by')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Updated at')),
                ('updated_by', models.CharField(blank=True, max_length=20, null=True, verbose_name='Updated by')),
            ],
            options={
                'db_table': 'design_component',
                'ordering': ('seq',),
                'managed': False,
            },
        ),
    ]
