# Generated by Django 5.0.6 on 2024-05-16 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RimsCpSetBranch',
            fields=[
                ('customer_guid', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='Customer guid')),
                ('branch_guid', models.CharField(db_column='BRANCH_GUID', max_length=32, verbose_name='Branch guid')),
                ('branch_code', models.CharField(blank=True, db_column='BRANCH_CODE', max_length=20, null=True, verbose_name='Branch Code')),
                ('branch_name', models.CharField(blank=True, db_column='BRANCH_NAME', max_length=60, null=True, verbose_name='Branch Name')),
                ('branch_add', models.TextField(blank=True, db_column='BRANCH_ADD', null=True, verbose_name='Branch Address')),
                ('branch_tel', models.CharField(blank=True, db_column='BRANCH_TEL', max_length=30, null=True, verbose_name='Branch Telephone')),
                ('branch_fax', models.CharField(blank=True, db_column='BRANCH_FAX', max_length=30, null=True, verbose_name='Branch Fax')),
                ('script_tablename', models.CharField(blank=True, db_column='SCRIPT_TABLENAME', max_length=20, null=True, verbose_name='Script Table Name')),
                ('set_ratio', models.FloatField(blank=True, db_column='SET_RATIO', null=True, verbose_name='Set Ratio')),
                ('set_priority', models.IntegerField(blank=True, db_column='SET_PRIORITY', null=True, verbose_name='Set Priority')),
                ('created_at', models.DateTimeField(blank=True, db_column='CREATED_AT', null=True, verbose_name='Created At')),
                ('created_by', models.CharField(blank=True, db_column='CREATED_BY', max_length=30, null=True, verbose_name='Created By')),
                ('updated_at', models.DateTimeField(blank=True, db_column='UPDATED_AT', null=True, verbose_name='Updated At')),
                ('updated_by', models.CharField(blank=True, db_column='UPDATED_BY', max_length=30, null=True, verbose_name='Updated By')),
                ('set_supplier_code', models.CharField(blank=True, db_column='SET_SUPPLIER_CODE', max_length=20, null=True, verbose_name='Set Supplier Code')),
                ('set_customer_code', models.CharField(blank=True, db_column='SET_CUSTOMER_CODE', max_length=20, null=True, verbose_name='Set Customer Code')),
                ('sshhostname', models.CharField(blank=True, db_column='sshHostname', max_length=60, null=True, verbose_name='SSH Hostname')),
                ('sshport', models.IntegerField(blank=True, db_column='sshPort', null=True, verbose_name='SSH Port')),
                ('sshuser', models.CharField(blank=True, db_column='sshUser', max_length=30, null=True, verbose_name='SSH User')),
                ('sshpass', models.CharField(blank=True, db_column='sshPass', max_length=30, null=True, verbose_name='SSH Password')),
                ('databaset_default', models.CharField(blank=True, max_length=50, null=True, verbose_name='Default Database')),
                ('mysql_user', models.CharField(blank=True, max_length=30, null=True, verbose_name='MySQL User')),
                ('mysql_pass', models.CharField(blank=True, max_length=30, null=True, verbose_name='MySQL Password')),
                ('sshcdesthost', models.CharField(blank=True, db_column='sshCDestHost', max_length=50, null=True, verbose_name='SSH CDest Host')),
                ('sshcdestport', models.IntegerField(blank=True, db_column='sshCDestPort', null=True, verbose_name='SSH CDest Port')),
                ('sshcsourceport', models.IntegerField(blank=True, db_column='sshCSourcePort', null=True, verbose_name='SSH CSource Port')),
                ('script_database_tablename', models.CharField(blank=True, max_length=40, null=True, verbose_name='Script Database Table Name')),
                ('outlet_code_acc', models.CharField(blank=True, db_column='OUTLET_CODE_ACC', max_length=20, null=True, verbose_name='Outlet Code ACC')),
                ('periodendon', models.IntegerField(blank=True, db_column='PeriodEndOn', null=True, verbose_name='Period End On')),
                ('lastrecaldatetime', models.DateTimeField(blank=True, db_column='LastRecalDateTime', null=True, verbose_name='Last Recalculation Datetime')),
                ('recaltime', models.TimeField(blank=True, db_column='RecalTime', null=True, verbose_name='Recalculation Time')),
                ('nontrade_as_stock', models.SmallIntegerField(blank=True, null=True, verbose_name='Non-Trade as Stock')),
                ('set_active', models.SmallIntegerField(blank=True, null=True, verbose_name='Set Active')),
                ('is_dc', models.SmallIntegerField(blank=True, null=True, verbose_name='Is DC')),
                ('rep_all_ads', models.SmallIntegerField(blank=True, null=True, verbose_name='Rep All Ads')),
                ('branch_desc', models.CharField(blank=True, max_length=20, null=True, verbose_name='Branch Description')),
                ('fifo_calc', models.SmallIntegerField(blank=True, null=True, verbose_name='FIFO Calculation')),
            ],
            options={
                'db_table': 'rims_cp_set_branch',
                'ordering': ('customer_guid', 'branch_code'),
                'managed': False,
            },
        ),
    ]
