# Generated by Django 5.0.6 on 2024-05-16 10:46

import _lib.panda
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DesignCot',
            fields=[
                ('cot_guid', models.CharField(default=_lib.panda.panda_uuid, editable=False, max_length=32, primary_key=True, serialize=False, verbose_name='COT guid')),
                ('customer_guid', models.CharField(max_length=32, verbose_name='Customer guid')),
                ('tab_guid', models.CharField(max_length=32, verbose_name='Tab guid')),
                ('cot_group', models.CharField(blank=True, max_length=120, null=True, verbose_name='COT Group')),
                ('cot_seq', models.SmallIntegerField(blank=True, null=True, verbose_name='COT Sequence')),
                ('cot_description', models.CharField(blank=True, max_length=120, null=True, verbose_name='COT Description')),
                ('cot_value', models.TextField(blank=True, null=True, verbose_name='COT Value')),
                ('isactive', models.SmallIntegerField(blank=True, null=True, verbose_name='Is Active')),
                ('isdeleted', models.SmallIntegerField(blank=True, null=True, verbose_name='Is Deleted')),
                ('created_at', models.DateTimeField(blank=True, null=True, verbose_name='Created at')),
                ('created_by', models.CharField(blank=True, max_length=32, null=True, verbose_name='Created by')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Updated at')),
                ('updated_by', models.CharField(blank=True, max_length=32, null=True, verbose_name='Updated by')),
            ],
            options={
                'db_table': 'design_cot',
                'managed': False,
            },
        ),
    ]
