# Generated by Django 5.0.6 on 2024-05-16 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TtaListCalMain',
            fields=[
                ('cal_guid', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='Cal guid')),
                ('customer_guid', models.CharField(blank=True, max_length=32, null=True, verbose_name='Customer guid')),
                ('docdate', models.DateField(blank=True, null=True, verbose_name='Document Date')),
                ('outlet', models.CharField(max_length=32, verbose_name='Outlet')),
                ('sup_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='Supplier Code')),
                ('sup_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Supplier Name')),
                ('brand', models.CharField(blank=True, max_length=20, null=True, verbose_name='Brand')),
                ('brand_desc', models.CharField(blank=True, max_length=100, null=True, verbose_name='Brand Description')),
                ('gr_amt', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True, verbose_name='GR Amount')),
                ('gr_surchg', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True, verbose_name='GR Surcharge')),
                ('debitamt', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True, verbose_name='Debit Amount')),
                ('debit_surchg', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True, verbose_name='Debit Surcharge')),
                ('creditamt', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True, verbose_name='Credit Amount')),
                ('credit_surchg', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True, verbose_name='Credit Surcharge')),
                ('pdnamt', models.DecimalField(blank=True, db_column='PDNamt', decimal_places=2, max_digits=16, null=True, verbose_name='PDN Amount')),
                ('pcnamt', models.DecimalField(blank=True, db_column='PCNamt', decimal_places=2, max_digits=16, null=True, verbose_name='PCN Amount')),
                ('created_at', models.DateTimeField(blank=True, null=True, verbose_name='Created at')),
            ],
            options={
                'db_table': 'tta_list_cal_main',
                'ordering': ('cal_guid',),
                'managed': False,
            },
        ),
    ]
