# Generated by Django 5.0.6 on 2024-05-16 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('_mc_tta_list', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TtaListPromotionSupport',
            fields=[
                ('list_guid', models.OneToOneField(db_column='list_guid', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='_mc_tta_list.ttalist', verbose_name='List guid')),
                ('list_link_guid', models.CharField(blank=True, max_length=32, null=True, verbose_name='List Link guid')),
                ('promotion_guid', models.CharField(blank=True, editable=False, max_length=36, verbose_name='Promotion Support guid')),
                ('revision', models.CharField(blank=True, max_length=100, null=True, verbose_name='Revision')),
                ('customer_guid', models.CharField(max_length=32, verbose_name='Customer guid')),
                ('refno', models.CharField(editable=False, max_length=20, verbose_name='Reference No.')),
                ('middle_year_big_sales_value', models.FloatField(blank=True, null=True, verbose_name='Middle Year Big Sales Value')),
                ('middle_year_big_sales_type', models.CharField(blank=True, max_length=200, null=True, verbose_name='Middle Year Big Sales Type')),
                ('middle_year_big_sales_value_type', models.CharField(blank=True, max_length=200, null=True, verbose_name='Middle Year Big Sales Value Type')),
                ('middle_year_big_sales_date_to', models.CharField(blank=True, max_length=200, null=True, verbose_name='Middle Year Big Sales Date To')),
                ('middle_year_big_sales_date_from', models.CharField(blank=True, max_length=200, null=True, verbose_name='Middle Year Big Sales Date From')),
                ('top_brand_value', models.FloatField(blank=True, null=True, verbose_name='Top Brand Value')),
                ('top_brand_type', models.CharField(blank=True, max_length=200, null=True, verbose_name='Top Brand Type')),
                ('top_brand_value_type', models.CharField(blank=True, max_length=200, null=True, verbose_name='Top Brand Value Type')),
                ('top_brand_date_to', models.CharField(blank=True, max_length=200, null=True, verbose_name='Top Brand Date To')),
                ('top_brand_date_from', models.CharField(blank=True, max_length=200, null=True, verbose_name='Top Brand Date From')),
                ('anniversary_value', models.FloatField(blank=True, null=True, verbose_name='Anniversary Value')),
                ('anniversary_type', models.CharField(blank=True, max_length=200, null=True, verbose_name='Anniversary Type')),
                ('anniversary_value_type', models.CharField(blank=True, max_length=200, null=True, verbose_name='Anniversary Value Type')),
                ('anniversary_date_to', models.CharField(blank=True, max_length=200, null=True, verbose_name='Anniversary Date To')),
                ('anniversary_date_from', models.CharField(blank=True, max_length=200, null=True, verbose_name='Anniversary Date From')),
                ('gawai_value', models.FloatField(blank=True, null=True, verbose_name='Gawai Value')),
                ('gawai_type', models.CharField(blank=True, max_length=200, null=True, verbose_name='Gawai Type')),
                ('gawai_value_type', models.CharField(blank=True, max_length=200, null=True, verbose_name='Gawai Value Type')),
                ('gawai_date_to', models.CharField(blank=True, max_length=200, null=True, verbose_name='Gawai Date To')),
                ('gawai_date_from', models.CharField(blank=True, max_length=200, null=True, verbose_name='Gawai Date From')),
                ('gawai_sales_value', models.FloatField(blank=True, null=True, verbose_name='Gawai Sales Value')),
                ('gawai_sales_type', models.CharField(blank=True, max_length=200, null=True, verbose_name='Gawai Sales Type')),
                ('gawai_sales_value_type', models.CharField(blank=True, max_length=200, null=True, verbose_name='Gawai Sales Value Type')),
                ('gawai_sales_date_to', models.CharField(blank=True, max_length=200, null=True, verbose_name='Gawai Sales Date To')),
                ('gawai_sales_date_from', models.CharField(blank=True, max_length=200, null=True, verbose_name='Gawai Sales Date From')),
                ('anniversary_sales_value', models.FloatField(blank=True, null=True, verbose_name='Anniversary Sales Value')),
                ('anniversary_sales_type', models.CharField(blank=True, max_length=200, null=True, verbose_name='Anniversary Sales Type')),
                ('anniversary_sales_value_type', models.CharField(blank=True, max_length=200, null=True, verbose_name='Anniversary Sales Value Type')),
                ('anniversary_sales_date_to', models.CharField(blank=True, max_length=200, null=True, verbose_name='Anniversary Sales Date To')),
                ('anniversary_sales_date_from', models.CharField(blank=True, max_length=200, null=True, verbose_name='Anniversary Sales Date From')),
                ('chinese_new_year_sales_value', models.FloatField(blank=True, null=True, verbose_name='Chinese New Year Sales Value')),
                ('chinese_new_year_sales_type', models.CharField(blank=True, max_length=200, null=True, verbose_name='Chinese New Year Sales Type')),
                ('chinese_new_year_sales_value_type', models.CharField(blank=True, max_length=200, null=True, verbose_name='Chinese New Year Sales Value Type')),
                ('chinese_new_year_sales_date_to', models.CharField(blank=True, max_length=200, null=True, verbose_name='Chinese New Year Sales Date To')),
                ('chinese_new_year_sales_date_from', models.CharField(blank=True, max_length=200, null=True, verbose_name='Chinese New Year Sales Date From')),
                ('hari_raya_sales_value', models.FloatField(blank=True, null=True, verbose_name='Hari Raya Sales Value')),
                ('hari_raya_sales_type', models.CharField(blank=True, max_length=200, null=True, verbose_name='Hari Raya Sales Type')),
                ('hari_raya_sales_value_type', models.CharField(blank=True, max_length=200, null=True, verbose_name='Hari Raya Sales Value Type')),
                ('hari_raya_sales_date_to', models.CharField(blank=True, max_length=200, null=True, verbose_name='Hari Raya Sales Date To')),
                ('hari_raya_sales_date_from', models.CharField(blank=True, max_length=200, null=True, verbose_name='Hari Raya Sales Date From')),
                ('christmas_sales_value', models.FloatField(blank=True, null=True, verbose_name='Christmas Sales Value')),
                ('christmas_sales_type', models.CharField(blank=True, max_length=200, null=True, verbose_name='Christmas Sales Type')),
                ('christmas_sales_value_type', models.CharField(blank=True, max_length=200, null=True, verbose_name='Christmas Sales Value Type')),
                ('christmas_sales_date_to', models.CharField(blank=True, max_length=200, null=True, verbose_name='Christmas Sales Date To')),
                ('christmas_sales_date_from', models.CharField(blank=True, max_length=200, null=True, verbose_name='Christmas Sales Date From')),
                ('promotion_commission_value', models.FloatField(blank=True, null=True, verbose_name='Promotion Commission Value')),
                ('promotion_commission_type', models.CharField(blank=True, max_length=200, null=True, verbose_name='Promotion Commission Type')),
                ('promotion_commission_value_type', models.CharField(blank=True, max_length=200, null=True, verbose_name='Promotion Commission Value Type')),
                ('promotion_commission_date_to', models.CharField(blank=True, max_length=200, null=True, verbose_name='Promotion Commission Date To')),
                ('promotion_commission_date_from', models.CharField(blank=True, max_length=200, null=True, verbose_name='Promotion Commission Date From')),
                ('created_at', models.DateTimeField(blank=True, null=True, verbose_name='Created at')),
                ('created_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='Created by')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Updated at')),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='Updated by')),
            ],
            options={
                'verbose_name': 'TTA List Promotion Support Detail',
                'verbose_name_plural': 'TTA List Promotion Support Details',
                'db_table': 'tta_list_promotionsupport',
                'ordering': ('refno',),
                'managed': False,
            },
        ),
    ]
