# Generated by Django 5.0.6 on 2024-05-16 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RimsCustomerData',
            fields=[
                ('data_guid', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='Data guid')),
                ('customer_guid', models.CharField(max_length=32, verbose_name='Customer guid')),
                ('list_guid', models.CharField(max_length=32, verbose_name='List guid')),
                ('module_type', models.CharField(blank=True, max_length=60, null=True, verbose_name='Module Type')),
                ('date_from', models.DateField(blank=True, null=True, verbose_name='Date From')),
                ('date_to', models.DateField(blank=True, null=True, verbose_name='Date To')),
                ('data_json', models.JSONField(blank=True, null=True, verbose_name='Data JSON')),
                ('created_at', models.DateTimeField(blank=True, null=True, verbose_name='Created At')),
                ('created_by', models.CharField(blank=True, max_length=32, null=True, verbose_name='Created By')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Updated At')),
                ('updated_by', models.CharField(blank=True, max_length=32, null=True, verbose_name='Updated By')),
            ],
            options={
                'db_table': 'rims_customer_data',
                'managed': False,
            },
        ),
    ]
