# Generated by Django 5.0.6 on 2024-05-16 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TtaLogs',
            fields=[
                ('log_guid', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='Log guid')),
                ('customer_guid', models.CharField(max_length=32, verbose_name='Customer guid')),
                ('log_module', models.CharField(blank=True, max_length=255, null=True, verbose_name='Log Module')),
                ('log_ref', models.CharField(blank=True, max_length=60, null=True, verbose_name='Log Reference')),
                ('created_at', models.DateTimeField(blank=True, null=True, verbose_name='Created at')),
                ('created_by', models.CharField(blank=True, max_length=60, null=True, verbose_name='Created by')),
                ('log_json', models.JSONField(blank=True, null=True, verbose_name='Log JSON')),
                ('remark', models.JSONField(blank=True, null=True, verbose_name='Remark')),
            ],
            options={
                'db_table': 'tta_logs',
                'ordering': ('log_guid', 'log_ref'),
                'managed': False,
            },
        ),
    ]
