# Generated by Django 5.0.6 on 2024-05-16 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TtaListStatusTrans',
            fields=[
                ('customer_guid', models.CharField(blank=True, max_length=32, null=True, verbose_name='Customer guid')),
                ('list_guid', models.CharField(blank=True, max_length=32, null=True, verbose_name='List guid')),
                ('trans_guid', models.CharField(editable=False, max_length=32, primary_key=True, serialize=False, verbose_name='Transaction guid')),
                ('status_key', models.CharField(blank=True, max_length=30, null=True, verbose_name='Status Key')),
                ('status_description', models.CharField(blank=True, max_length=32, null=True, verbose_name='Status Description')),
                ('status_process', models.CharField(blank=True, max_length=60, null=True, verbose_name='Status Process')),
                ('status', models.SmallIntegerField(blank=True, null=True, verbose_name='Status')),
                ('created_at', models.DateTimeField(blank=True, null=True, verbose_name='Created at')),
                ('created_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='Created by')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Updated at')),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='Updated by')),
            ],
            options={
                'db_table': 'tta_list_status_trans',
                'managed': False,
            },
        ),
    ]
