# Generated by Django 5.0.6 on 2024-05-16 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TtaListForm',
            fields=[
                ('list_guid_c', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='List guid C')),
                ('tab_guid', models.CharField(blank=True, max_length=32, null=True, verbose_name='Tab guid')),
                ('group', models.CharField(blank=True, max_length=200, null=True, verbose_name='Group')),
                ('seq', models.IntegerField(blank=True, null=True, verbose_name='Sequence')),
                ('key_description', models.CharField(blank=True, max_length=100, null=True, verbose_name='Key Description')),
                ('left_option', models.CharField(blank=True, max_length=100, null=True, verbose_name='Left Option')),
                ('varchar_1', models.CharField(blank=True, max_length=120, null=True, verbose_name='First Var Char')),
                ('type_1', models.CharField(blank=True, max_length=32, null=True, verbose_name='First Type')),
                ('val_1', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='First Value')),
                ('text_1', models.TextField(blank=True, null=True, verbose_name='First Text')),
                ('type_2', models.CharField(blank=True, max_length=32, null=True, verbose_name='Second Type')),
                ('val_2', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Second Value')),
                ('type_3', models.CharField(blank=True, max_length=32, null=True, verbose_name='Third Type')),
                ('val_3', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Third Value')),
                ('created_at', models.DateTimeField(blank=True, null=True, verbose_name='Created At')),
                ('created_by', models.CharField(blank=True, max_length=32, null=True, verbose_name='Created By')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Updated At')),
                ('updated_by', models.CharField(blank=True, max_length=32, null=True, verbose_name='Updated By')),
            ],
            options={
                'db_table': 'tta_list_form',
                'ordering': ('group', 'seq'),
                'managed': False,
            },
        ),
    ]
