# Generated by Django 5.0.6 on 2024-05-16 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccUser',
            fields=[
                ('acc_user_guid', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='Account User guid')),
                ('acc_user_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Account User Identifier')),
                ('acc_user_password', models.CharField(blank=True, max_length=15, null=True, verbose_name='Account User Password')),
                ('acc_user_name', models.CharField(blank=True, max_length=60, null=True, verbose_name='Account User Name')),
                ('acc_user_instance', models.CharField(blank=True, max_length=120, null=True, verbose_name='Account User Instance')),
                ('acc_user_instance_variable', models.CharField(blank=True, max_length=120, null=True, verbose_name='Account User Instance Variable')),
                ('created_at', models.DateTimeField(blank=True, null=True, verbose_name='Created at')),
                ('created_by', models.CharField(blank=True, max_length=255, null=True, verbose_name='Created by')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Updated at')),
                ('updated_by', models.CharField(blank=True, max_length=255, null=True, verbose_name='Updated by')),
                ('acc_guid', models.CharField(max_length=32, verbose_name='Account guid')),
                ('acc_name', models.CharField(blank=True, max_length=120, null=True, verbose_name='Account Name')),
                ('user_count', models.CharField(blank=True, max_length=120, null=True, verbose_name='Number of User')),
                ('driver_count', models.CharField(blank=True, max_length=120, null=True, verbose_name='Number of Driver')),
                ('isactive', models.SmallIntegerField(blank=True, null=True, verbose_name='Is Active')),
                ('acc_user_location', models.CharField(blank=True, max_length=120, null=True, verbose_name='Account User Location')),
            ],
            options={
                'db_table': 'acc_user',
                'managed': False,
            },
        ),
    ]
