# Generated by Django 5.0.6 on 2024-05-27 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TtaListOutlet',
            fields=[
                ('tta_outlet_guid', models.CharField(blank=True, editable=False, max_length=32, primary_key=True, serialize=False, verbose_name='TTA List Exclude Outlet guid')),
                ('outlet_type', models.CharField(blank=True, max_length=200, null=True, verbose_name='Outlet Type')),
                ('outlet_code', models.CharField(blank=True, max_length=200, null=True, verbose_name='Outlet Code')),
                ('outlet_label', models.CharField(blank=True, max_length=200, null=True, verbose_name='Outlet Label')),
            ],
            options={
                'verbose_name': 'TTA List Outlet Detail',
                'verbose_name_plural': 'TTA List Outlet Details',
                'db_table': 'tta_list_outlet',
                'ordering': ('list_guid',),
                'managed': False,
            },
        ),
    ]
