# Generated by Django 5.0.6 on 2024-05-27 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TtaListExcludeOutlet',
            fields=[
                ('tta_exclude_outlet_guid', models.CharField(blank=True, editable=False, max_length=32, primary_key=True, serialize=False, verbose_name='TTA List Exclude Outlet guid')),
                ('outlet', models.CharField(blank=True, max_length=200, null=True, verbose_name='Outlet')),
            ],
            options={
                'verbose_name': 'TTA List Exclude Outlet Detail',
                'verbose_name_plural': 'TTA List Exclude Outlet Details',
                'db_table': 'tta_list_excludeoutlet',
                'ordering': ('list_guid',),
                'managed': False,
            },
        ),
    ]
