# Generated by Django 5.0.6 on 2024-05-17 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TtaListTradingBrand',
            fields=[
                ('brand_code', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='Brand code')),
                ('customer_guid', models.CharField(max_length=32, verbose_name='Customer guid')),
                ('refno', models.CharField(editable=False, max_length=20, verbose_name='Reference No.')),
            ],
            options={
                'verbose_name': 'TTA List Trading Brand Detail',
                'verbose_name_plural': 'TTA List Trading Brands Details',
                'db_table': 'tta_list_brand',
                'ordering': ('refno',),
                'managed': False,
            },
        ),
    ]
