# Generated by Django 5.0.6 on 2024-05-16 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TtaList_ts',
            fields=[
                ('list_guid', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='List guid')),
                ('list_link_guid', models.CharField(blank=True, max_length=32, null=True, verbose_name='List Link guid')),
                ('revision', models.CharField(blank=True, max_length=100, null=True, verbose_name='Revision')),
                ('customer_guid', models.CharField(max_length=32, verbose_name='Customer guid')),
                ('refno', models.CharField(max_length=20, verbose_name='Reference Number')),
                ('supplier_guid', models.CharField(max_length=32, verbose_name='Supplier guid')),
                ('supplier_code', models.CharField(blank=True, max_length=15, null=True, verbose_name='Supplier Code')),
                ('supplier_name', models.CharField(blank=True, max_length=60, null=True, verbose_name='Supplier Name')),
                ('bill_supp_guid', models.CharField(blank=True, max_length=32, null=True, verbose_name='Bill Supplier guid')),
                ('bill_supp_code', models.CharField(blank=True, max_length=15, null=True, verbose_name='Bill Supplier Code')),
                ('bill_supp_name', models.CharField(blank=True, max_length=60, null=True, verbose_name='Bill Supplier Name')),
                ('negotiation_year', models.TextField(blank=True, null=True, verbose_name='Negotiation Year')),
                ('co_reg_no', models.CharField(blank=True, max_length=32, null=True, verbose_name='Company Registration Number')),
                ('tta_period_from', models.CharField(blank=True, max_length=32, null=True, verbose_name='Tta Period From')),
                ('tta_period_to', models.CharField(blank=True, max_length=32, null=True, verbose_name='Tta Period To')),
                ('internal_pic', models.CharField(blank=True, max_length=60, null=True, verbose_name='Internal PIC')),
                ('trading_group', models.CharField(blank=True, max_length=60, null=True, verbose_name='Trading Group')),
                ('trading_type', models.CharField(blank=True, max_length=60, null=True, verbose_name='Trading Type')),
                ('delivery_mode', models.CharField(blank=True, max_length=60, null=True, verbose_name='Delivery Mode')),
                ('returnable', models.CharField(blank=True, max_length=10, null=True, verbose_name='Returnable')),
                ('supplier_pic', models.CharField(blank=True, max_length=60, null=True, verbose_name='Supplier PIC')),
                ('supplier_pic_name', models.CharField(blank=True, max_length=60, null=True, verbose_name='Supplier PIC Name')),
                ('supplier_pic_position', models.CharField(blank=True, max_length=60, null=True, verbose_name='Supplier PIC Position')),
                ('supplier_pic_contact', models.CharField(blank=True, max_length=60, null=True, verbose_name='Supplier PIC Contact')),
                ('supplier_pic_email', models.CharField(blank=True, max_length=60, null=True, verbose_name='Supplier PIC Email')),
                ('banner', models.TextField(blank=True, null=True, verbose_name='Banner')),
                ('outlet', models.TextField(blank=True, null=True, verbose_name='Outlet')),
                ('supplier_profile', models.JSONField(blank=True, null=True, verbose_name='Supplier Profile')),
                ('purchase_n_rebates', models.JSONField(blank=True, null=True, verbose_name='Purchase and Rebates')),
                ('payment_n_discount', models.JSONField(blank=True, null=True, verbose_name='Payment and Discount')),
                ('stock_n_deliveries', models.JSONField(blank=True, null=True, verbose_name='Stock and Deliveries')),
                ('administration_fees', models.JSONField(blank=True, null=True, verbose_name='Administration Fees')),
                ('business_growth_support', models.JSONField(blank=True, null=True, verbose_name='Business Growth Support')),
                ('promotion_support', models.JSONField(blank=True, null=True, verbose_name='Promotion Support')),
                ('display_incentive', models.JSONField(blank=True, null=True, verbose_name='Display Incentive')),
                ('marketing_support', models.JSONField(blank=True, null=True, verbose_name='Marketing Support')),
                ('e_commerce_support', models.JSONField(blank=True, null=True, verbose_name='E-commerce Support')),
                ('concess_n_consign', models.JSONField(blank=True, null=True, verbose_name='Concession and Consignment')),
                ('data_sharing_plan', models.JSONField(blank=True, null=True, verbose_name='Data Sharing Plan')),
                ('condition_of_trade', models.JSONField(blank=True, null=True, verbose_name='Condition of Trade')),
                ('effective_date', models.CharField(blank=True, max_length=32, null=True, verbose_name='Effective Date')),
                ('created_at', models.DateTimeField(blank=True, null=True, verbose_name='Created at')),
                ('created_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='Created by')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Updated at')),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='Updated by')),
                ('submit_date', models.DateTimeField(blank=True, null=True, verbose_name='Submit Date')),
                ('submit_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='Submit by')),
                ('approve_date', models.DateTimeField(blank=True, null=True, verbose_name='Approve Date')),
                ('approve_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='Approve by')),
                ('reject_at', models.DateTimeField(blank=True, null=True, verbose_name='Reject Date')),
                ('reject_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='Reject by')),
                ('list_status', models.CharField(blank=True, max_length=20, null=True, verbose_name='List Status')),
                ('ecommerce_support', models.JSONField(blank=True, null=True, verbose_name='E-commerce Support')),
                ('purchase_rebate_tier', models.JSONField(blank=True, null=True, verbose_name='Purchase Rebate Tier')),
            ],
            options={
                'db_table': 'tta_list',
                'ordering': ('refno', 'list_guid'),
                'managed': False,
            },
        ),
    ]
