# Generated by Django 5.0.6 on 2024-05-16 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('_mc_tta_list', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TtaListPurchaseNRebates',
            fields=[
                ('list_guid', models.OneToOneField(db_column='list_guid', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='_mc_tta_list.ttalist', verbose_name='List guid')),
                ('list_link_guid', models.CharField(blank=True, max_length=32, null=True, verbose_name='List Link guid')),
                ('purchase_guid', models.CharField(blank=True, editable=False, max_length=36, verbose_name='Purchase guid')),
                ('revision', models.CharField(blank=True, max_length=100, null=True, verbose_name='Revision')),
                ('customer_guid', models.CharField(max_length=32, verbose_name='Customer guid')),
                ('refno', models.CharField(editable=False, max_length=20, verbose_name='Reference No.')),
                ('unconditional_rebate_value', models.FloatField(blank=True, null=True, verbose_name='Unconditional Rebate Value')),
                ('unconditional_rebate_type', models.CharField(blank=True, max_length=200, null=True, verbose_name='Unconditional Rebate Type')),
                ('unconditional_rebate_value_type', models.CharField(blank=True, max_length=200, null=True, verbose_name='Unconditional Rebate Value Type')),
                ('commission_value', models.FloatField(blank=True, null=True, verbose_name='Commission Value')),
                ('commission_type', models.CharField(blank=True, max_length=200, null=True, verbose_name='Commission Type')),
                ('commission_value_type', models.CharField(blank=True, max_length=200, null=True, verbose_name='Commission Value Type')),
                ('auto_replenishment_rebate_value', models.FloatField(blank=True, null=True, verbose_name='Auto Replenishment Rebate Value')),
                ('auto_replenishment_rebate_type', models.CharField(blank=True, max_length=200, null=True, verbose_name='Auto Replenishment Rebate Type')),
                ('auto_replenishment_rebate_value_type', models.CharField(blank=True, max_length=200, null=True, verbose_name='Auto Replenishment Rebate Value Type')),
                ('common_assortment_rebate_value', models.FloatField(blank=True, null=True, verbose_name='Common Assortment Rebate Value')),
                ('common_assortment_rebate_type', models.CharField(blank=True, max_length=200, null=True, verbose_name='Common Assortment Rebate Type')),
                ('common_assortment_rebate_value_type', models.CharField(blank=True, max_length=200, null=True, verbose_name='Common Assortment Rebate Value Type')),
                ('monthly_discount_value', models.FloatField(blank=True, null=True, verbose_name='Monthly Discount Rebate Value')),
                ('monthly_discount_type', models.CharField(blank=True, max_length=200, null=True, verbose_name='Monthly Discount Rebate Type')),
                ('monthly_discount_value_type', models.CharField(blank=True, max_length=200, null=True, verbose_name='Monthly Discount Value Type')),
                ('target_period_type', models.CharField(blank=True, max_length=200, null=True, verbose_name='Target Period Rebate Type')),
                ('target_purchase_tier_1_value1', models.FloatField(blank=True, null=True, verbose_name='Target Purchase Tier 1 Value 1')),
                ('target_purchase_tier_1_value2', models.FloatField(blank=True, null=True, verbose_name='Target Purchase Tier 1 Value 2')),
                ('target_purchase_tier_1_type1', models.CharField(blank=True, max_length=200, null=True, verbose_name='Target Purchase Tier 1 Type 1')),
                ('target_purchase_tier_1_type2', models.CharField(blank=True, max_length=200, null=True, verbose_name='Target Purchase Tier 1 Type 2')),
                ('target_purchase_tier_1_value_type', models.CharField(blank=True, max_length=200, null=True, verbose_name='Target Purchase Tier 1 Value Type')),
                ('target_purchase_tier_2_value1', models.FloatField(blank=True, null=True, verbose_name='Target Purchase Tier 2 Value 1')),
                ('target_purchase_tier_2_value2', models.FloatField(blank=True, null=True, verbose_name='Target Purchase Tier 2 Value 2')),
                ('target_purchase_tier_2_type1', models.CharField(blank=True, max_length=200, null=True, verbose_name='Target Purchase Tier 2 Type 1')),
                ('target_purchase_tier_2_type2', models.CharField(blank=True, max_length=200, null=True, verbose_name='Target Purchase Tier 2 Type 2')),
                ('target_purchase_tier_2_value_type', models.CharField(blank=True, max_length=200, null=True, verbose_name='Target Purchase Tier 2 Value Type')),
                ('target_purchase_tier_3_value1', models.FloatField(blank=True, null=True, verbose_name='Target Purchase Tier 3 Value 1')),
                ('target_purchase_tier_3_value2', models.FloatField(blank=True, null=True, verbose_name='Target Purchase Tier 3 Value 2')),
                ('target_purchase_tier_3_type1', models.CharField(blank=True, max_length=200, null=True, verbose_name='Target Purchase Tier 3 Type 1')),
                ('target_purchase_tier_3_type2', models.CharField(blank=True, max_length=200, null=True, verbose_name='Target Purchase Tier 3 Type 2')),
                ('target_purchase_tier_3_value_type', models.CharField(blank=True, max_length=200, null=True, verbose_name='Target Purchase Tier 3 Value Type')),
                ('target_growth_tier_1_value1', models.FloatField(blank=True, null=True, verbose_name='Target Growth Tier 1 Value 1')),
                ('target_growth_tier_1_value2', models.FloatField(blank=True, null=True, verbose_name='Target Growth Tier 1 Value 2')),
                ('target_growth_tier_1_type1', models.CharField(blank=True, max_length=200, null=True, verbose_name='Target Growth Tier 1 Type 1')),
                ('target_growth_tier_1_type2', models.CharField(blank=True, max_length=200, null=True, verbose_name='Target Growth Tier 1 Type 2')),
                ('target_growth_tier_1_type3', models.CharField(blank=True, max_length=200, null=True, verbose_name='Target Growth Tier 1 Type 3')),
                ('target_growth_tier_1_type4', models.CharField(blank=True, max_length=200, null=True, verbose_name='Target Growth Tier 1 Type 4')),
                ('target_growth_tier_1_value_type', models.CharField(blank=True, max_length=200, null=True, verbose_name='Target Growth Tier 1 Value Type')),
                ('target_growth_tier_2_value1', models.FloatField(blank=True, null=True, verbose_name='Target Growth Tier 2 Value 1')),
                ('target_growth_tier_2_value2', models.FloatField(blank=True, null=True, verbose_name='Target Growth Tier 2 Value 2')),
                ('target_growth_tier_2_type1', models.CharField(blank=True, max_length=200, null=True, verbose_name='Target Growth Tier 2 Type 1')),
                ('target_growth_tier_2_type2', models.CharField(blank=True, max_length=200, null=True, verbose_name='Target Growth Tier 2 Type 2')),
                ('target_growth_tier_2_type3', models.CharField(blank=True, max_length=200, null=True, verbose_name='Target Growth Tier 2 Type 3')),
                ('target_growth_tier_2_type4', models.CharField(blank=True, max_length=200, null=True, verbose_name='Target Growth Tier 2 Type 4')),
                ('target_growth_tier_2_value_type', models.CharField(blank=True, max_length=200, null=True, verbose_name='Target Growth Tier 2 Value Type')),
                ('target_growth_tier_3_value1', models.FloatField(blank=True, null=True, verbose_name='Target Growth Tier 3 Value 1')),
                ('target_growth_tier_3_value2', models.FloatField(blank=True, null=True, verbose_name='Target Growth Tier 3 Value 2')),
                ('target_growth_tier_3_type1', models.CharField(blank=True, max_length=200, null=True, verbose_name='Target Growth Tier 3 Type 1')),
                ('target_growth_tier_3_type2', models.CharField(blank=True, max_length=200, null=True, verbose_name='Target Growth Tier 3 Type 2')),
                ('target_growth_tier_3_type3', models.CharField(blank=True, max_length=200, null=True, verbose_name='Target Growth Tier 3 Type 3')),
                ('target_growth_tier_3_type4', models.CharField(blank=True, max_length=200, null=True, verbose_name='Target Growth Tier 3 Type 4')),
                ('target_growth_tier_3_value_type', models.CharField(blank=True, max_length=200, null=True, verbose_name='Target Growth Tier 3 Value Type')),
                ('created_at', models.DateTimeField(blank=True, null=True, verbose_name='Created at')),
                ('created_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='Created by')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Updated at')),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='Updated by')),
            ],
            options={
                'verbose_name': 'TTA List Purchase and Rebates Detail',
                'verbose_name_plural': 'TTA List Purchase and Rebates Details',
                'db_table': 'tta_list_purchasenrebates',
                'ordering': ['tta_list__refno'],
                'managed': False,
            },
        ),
    ]
